### ISSUE TITLE
No module named parsing

### ISSUE THREAD

**Issue by mediocregopher** [2ndQuadrant/ansible-ssh#1]
```
▻ ansible-ssh foo
Traceback (most recent call last):
  File "/home/mediocregopher/bin/ansible-ssh", line 9, in <module>
    from ansible.parsing import DataLoader
ImportError: No module named parsing
```

I get this error when trying to run ansible-ssh. I've tried it with both python2 and python3. This is with ansible 1.9.2 installed. My python isn't great, are there any steps I can take to help debugging this?

**Comment by amenonsen** [comment]
Sorry, I forgot to mention that I implemented this against `devel`, i.e. version 2. It should be possible to get it to work with 1.9, but I don't have the time (or the inclination to become familiar with the old code base) to do this.

The good news is that you can just clone the https://github.com/ansible/ansible repository and run ansible against it, even if you don't switch to 1.9 for anything else. The inventory format is backwards-compatible. All you need to do is make sure the `PYTHONPATH` environment variable includes the 2.x directory, e.g. `export PYTHONPATH=/home/mediocregopher/ansible/lib/ansible:$PYTHONPATH` when you run `ansible-ssh` (so you could write a two-line shell script that sets the environment variable and then runs `ansible-ssh $@`).

I'll close this issue now, but please feel free to write to me if you have trouble getting it working.

**Comment by mediocregopher** [comment]
Ah I gotcha, I'll give that a shot, thanks!

**Comment by shahdhruvin** [comment]
On **_OSX_** I was getting import errors:
**ImportError: No module named ansible.parsing.dataloader**
I figured that ansible libs are getting installed at below location, and so I set the PYTHONPATH as shown below, which fixed the problems:
**export PYTHONPATH=/usr/local/Cellar/ansible/2.0.0.2/libexec/lib/python2.7/site-packages/:$PYTHONPATH**

**Comment by RubaiyaBegum** [comment]
Am receiving below error while executing ansible API, Can someone help on this?

Traceback (most recent call last):
.
.
.
    from ansible.parsing.dataloader import DataLoader
ImportError: No module named parsing.dataloader

PYTHON PATH:

>>> import os
>>> os.environ['PYTHONPATH'].split(os.pathsep)
['/usr/lib/python2.6/site-packages/', '']
>>>

Path of dataloader
/usr/lib/python2.6/site-packages/ansible/parsing/dataloader.py

**Comment by mntoumi** [comment]
hello ... you can  consider to change the name of your script if it is named ansible
